<?php
  include('LunarMonth.php');
  $day = '2016-11-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2016-12-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2017-01-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2017-02-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2017-03-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2017-04-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2017-05-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2017-06-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2017-07-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2017-08-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2017-09-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2017-10-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2017-11-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2017-12-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2018-01-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2018-02-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  print('<br><br>');
  $day = '2018-03-08';
  $lunarm = new LunarMonth($day);
  print_r ($lunarm);
  
?>
